apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: team-apps
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - repoUrl: 'https://github.com/rstoermer/argotest'
            path: argo-apps
            targetRevision: 'main'
            project: 'pyro'
            appName: 'pyro-apps'
  template:
    metadata:
      name: '{{appName}}'
    spec:
      project: '{{project}}'
      source:
        repoURL: '{{repoUrl}}'
        targetRevision: '{{targetRevision}}'
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true