apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: team-applications
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - repoURL: 'https://github.com/rstoermer/argotest.git'
            path: argo-apps
            targetRevision: 'main'
            project: 'default'
            appName: 'pyro-apps'
  template:
    metadata:
      name: '{{appName}}'
    spec:
      project: '{{project}}'
      source:
        repoURL: '{{repoURL}}'
        targetRevision: '{{targetRevision}}'
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
