apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clickhouse-vectors-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/rstoermer/argotest.git'
    targetRevision: main
    path: clickhouse-vectors
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
