# Install via: helm install argocd argo/argo-cd --values hack/argo-values.yaml
# web-ui: kubectl port-forward service/argocd-server -n default 8080:443

redis-ha:
  enabled: false

controller:
  replicas: 1

server:
  replicas: 1

repoServer:
  replicas: 1

applicationSet:
  replicas: 1