apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: clickhouse-vectors
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: eu1-prod
        name: vector-device-eu1-prod
        envFile: values-eu1-prod.yaml
        vectorTemplate: device
      - cluster: eu1-prod
        name: vector-location-eu1-prod
        envFile: values-eu1-prod.yaml
        vectorTemplate: location
      - cluster: eu1-prod
        name: vector-procedure-eu1-prod
        envFile: values-eu1-prod.yaml
        vectorTemplate: procedure
  template:
    metadata:
      name: '{{name}}'
      namespace: team-pyro
    spec:
      syncPolicy:
        automated: {}
      project: pyro
      sources:
        - repoURL: 'https://helm.vector.dev'
          chart: vector
          targetRevision: 0.33.0
          helm:
            valueFiles:
            - $vectorValues/clickhouse-vectors/vectors/{{vectorTemplate}}.yaml
            - $vectorValues/clickhouse-vectors/values/{{envFile}}
            - $vectorValues/clickhouse-vectors/values/values.yaml
        - repoURL: 'https://github.com/rstoermer/argotest'
          targetRevision: main
          ref: vectorValues
          path: clickhouse-vectors
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: team-pyro
